Repository zarunbal/LogExpert, pull requests merged in 2021-11, with the labels that each got.

#193 Allow resize and add autosize to the filter box (close #177)
  src/LogExpert/Controls/LogWindow/LogWindow.cs
  src/LogExpert/Controls/LogWindow/LogWindow.designer.cs
  src/LogExpert/Controls/LogWindow/LogWindowEventHandlers.cs
  src/LogExpert/Controls/LogWindow/LogWindowsPublic.cs
  src/LogExpert/Extensions/ComboBoxExtensions.cs
  src/LogExpert/LogExpert.csproj
Labels: enhancement, Feature

#194 Import new highlight settings (instead of replace) (close #179)
  src/LogExpert/Config/ConfigManager.cs
  src/LogExpert/Config/ExportImportFlags.cs
  src/LogExpert/Dialogs/HilightDialog.Designer.cs
  src/LogExpert/Dialogs/HilightDialog.cs
  src/LogExpert/Dialogs/ImportSettingsDialog.Designer.cs
  src/LogExpert/Dialogs/ImportSettingsDialog.cs
Labels: enhancement, Feature

#192 Fix file order selection when using multi-file because it is not guaranteed by OS
  src/LogExpert/Controls/LogTabWindow/LogTabWindowPrivate.cs
Labels: enhancement

#203 Prevent ArgumentOutOfRangeException when navigating through Multifiles (close #202)
  src/LogExpert/Controls/LogWindow/LogWindowPrivate.cs
Labels: bug

#189 Check for an empty dir variable added
  src/LogExpert/Classes/Persister/Persister.cs
Labels: bug
